# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/axolotl/criminating/ungranular:output",
        "bakongo/isotactic/reitman/isotactic:output",
        "bakongo/tagboard/reitman/tagboard:output",
        "bakongo/blithesomely/triturature/hazelly:output",
        "bakongo/did/whipmaking/colchicin:output",
        "bakongo/unequivalent/endospermous/unworthily:output",
        "bakongo/monofilm/reitman/ballot:output",
        "bakongo/did/pneumas/southwood:output",
        "bakongo/did/santalum/billiton:output",
        "bakongo/labials/reitman/labials:output",
        "bakongo/did/syndeton/kittled:output",
        "bakongo/did/dustpans/unelegant:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/cassytha/launce/cassytha:output",
        "bakongo/archizoic/burgers/imu:output",
        "bakongo/excretolic/burgers/faison:output",
        "bakongo/rollet/reitman/rollet:output",
        "bakongo/chalastic/reitman/chalastic:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"bakongo_stylosporous_interwrought_synanthetic_trifistulary_interwrought_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["bakongo_stylosporous_interwrought_synanthetic_trifistulary_{chroot}/common_scripts/run_build.sh", "{chroot}", "bakongo_stylosporous_interwrought_synanthetic_trifistulary_interwrought_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
