# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/preconsuming/unqueened/mesogastral:output",
        "hypostasised/endospermous/entemple:output",
        "bakongo/oiw/burgers/abyssinian:output",
        "bakongo/ribaldly/unqueened/kerning:output",
        "hypostasised/endospermous/bikinis:output",
        "bakongo/yggdrasil/endospermous/elegised:output",
        "bakongo/did/whipmaking/colchicin:output",
        "bakongo/upglide/endospermous/ultrafeudal:output",
        "bakongo/preconsuming/reliers/snecket:output",
        "bakongo/monofilm/reitman/ballot:output",
        "bakongo/did/pneumas/southwood:output",
        "bakongo/did/santalum/billiton:output",
        "bakongo/monofilm/oxyosphresia/ashpan:output",
        "bakongo/did/syndeton/kittled:output",
        "bakongo/did/dustpans/unelegant:output",
        "bakongo/snatchers/unqueened/redeemedness:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/snatchers/reliers/antisexist:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"hypostasised_pseudosocial_watkin_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["hypostasised_pseudosocial_watkin_{chroot}/common_scripts/run_build.sh", "{chroot}", "hypostasised_pseudosocial_watkin_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
