# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/fulbright/bemire/unreparted:output",
        "worthington/covering/endospermous/homilist:output",
        "worthington/beslaved/torbert/hadendowa:output",
        "worthington/alevins/criminating/bucconinae:output",
        "worthington/cajole/pirtleville/unmaskers:output",
        "worthington/spelunkers/unqueened/semilethal:output",
        "worthington/beslaved/epikia/plastochrone:output",
        "worthington/dygogram/bemire/choteau:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/uneducated/oxyosphresia/rosttra:output",
        "worthington/uneducated/bemire/grinter:output",
        "worthington/filiciform/lysolecithin/schoolable:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/doornails/bemire/overletting:output",
        "worthington/knifing/lysolecithin/shnooks:output",
        "worthington/beslaved/benedicta/neutralize:output",
        "worthington/beslaved/dissembly/warrenne:output",
        "worthington/alevins/bemire/apoop:output",
        "worthington/psycholepsy/pentitol/peppiness:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_fulbright_lysolecithin_camuy_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_fulbright_lysolecithin_camuy_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_fulbright_lysolecithin_camuy_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
