# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/covering/endospermous/festatus:output",
        "worthington/covering/endospermous/homilist:output",
        "worthington/arienzo/lysolecithin/arienzo:output",
        "worthington/barksome/unqueened/styloglossal:output",
        "worthington/cajole/pirtleville/unmaskers:output",
        "worthington/spelunkers/unqueened/semilethal:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/primevity/colbertism/kaufmann:output",
        "worthington/uneducated/oxyosphresia/rosttra:output",
        "worthington/jasun/endospermous/encarnalised:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/uneducated/bemire/grinter:output",
        "worthington/primevity/criminating/harpylike:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_primevity_misauthorize_blacktree_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "worthington_primevity_misauthorize_blacktree_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
