# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/covering/endospermous/festatus:output",
        "worthington/covering/endospermous/homilist:output",
        "worthington/eclats/hereditably/philogarlic:output",
        "worthington/eclats/criminating/oligophrenic:output",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/barksome/unqueened/styloglossal:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/spelunkers/unqueened/semilethal:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/eclats/gnathostomi/rigs:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/uneducated/oxyosphresia/rosttra:output",
        "worthington/eclats/kufiyeh/pragmatistic:output",
        "worthington/eclats/spruiker/plateaus:output",
        "worthington/eclats/desaturation/patronizing:output",
        "worthington/eclats/lealness/glossotype:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_eclats_philistines_apthorp_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_eclats_philistines_apthorp_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_eclats_philistines_apthorp_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
