# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/covering/endospermous/brockages:output",
        "worthington/covering/endospermous/sparkingly:output",
        "worthington/pyritical/vincas/kaolinize:output",
        "worthington/pyritical/reitman/agastric:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/gastrostege/shawfowl/azosulphine:output",
        "worthington/covering/endospermous/goode:output",
        "worthington/callosities/decimated/eclipsises:output",
        "worthington/pyritical/decimated/enwreath:output",
        "worthington/covering/endospermous/absalom:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_pyritical_romipetal_chromoctye_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_pyritical_romipetal_chromoctye_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_pyritical_romipetal_chromoctye_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
