# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/covering/endospermous/festatus:output",
        "worthington/moldableness/thrasher/endospermous/croset:output",
        "gpss/arnaeus/thymy:output",
        "worthington/moldableness/thrasher/endospermous/coed:output",
        "worthington/backpacked/surprise/torsibility:output",
        "gpss/endospermous/trinities:output",
        "worthington/preshrinks/routhercock/enamour:output",
        "worthington/moldableness/thrasher/endospermous/saprophytes:output",
        "worthington/moldableness/thrasher/endospermous/incase:output",
        "worthington/moldableness/thrasher/endospermous/enormously:output",
        "worthington/sleided/stenobregma/synanthetic/dragginess:output",
        "worthington/moldableness/thrasher/endospermous/cankerberry:output",
        "worthington/moldableness/thrasher/endospermous/eligibility:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/moldableness/thrasher/endospermous/mispatched:output",
        "gpss/endospermous/obtruder:output",
        "worthington/moldableness/thrasher/endospermous/unadduceable:output",
        "worthington/joinerville/prickiest/pilotfish:output",
        "gpss/endospermous/chaves:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"gpss_ampasimenite_incremated_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["gpss_ampasimenite_incremated_{chroot}/common_scripts/run_build.sh", "{chroot}", "gpss_ampasimenite_incremated_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
