# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "biomorphic/reinstitute/endospermous/lazzaroni:output",
        "biomorphic/outtrumped/unstayedness/ddcu/baldberry:output",
        "biomorphic/reinstitute/endospermous/ailantine:output",
        "nonsovereign/endospermous/squareman:output",
        "biomorphic/reinstitute/romipetal/amazilia:output",
        "nonsovereign/podical/boyards:output",
        "biomorphic/abcissa/criminating/forseti:output",
        "biomorphic/untellable/surprise/pursuant:output",
        "nonsovereign/steamerless/hooklet:output",
        "nonsovereign/pinnotherian/procris:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"nonsovereign_tamure_preevidently_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["nonsovereign_tamure_preevidently_{chroot}/common_scripts/run_build.sh", "{chroot}", "nonsovereign_tamure_preevidently_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
