# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/backpacked/surprise/torsibility:output",
        "gpss/endospermous/trinities:output",
        "worthington/takt/hereditably/pregnancies:output",
        "worthington/covering/endospermous/yaksha:output",
        "worthington/monoid/reitman/monoid:output",
        "worthington/takt/springvale/otopathy:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "gpss/routhercock/alamanni:output",
        "worthington/covering/endospermous/grimme:output",
        "worthington/moldableness/thrasher/endospermous/cruciality:output",
        "worthington/covering/endospermous/haiduck:output",
        "worthington/covering/endospermous/rabulistic:output",
        "gpss/endospermous/chaves:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"gpss_synergidal_illene_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["gpss_synergidal_illene_{chroot}/common_scripts/run_build.sh", "{chroot}", "gpss_synergidal_illene_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
