# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/backpacked/dustpans/minimized:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/covering/endospermous/haematics:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/sculptitory/criminating/execrably:output",
        "worthington/monoid/reitman/monoid:output",
        "worthington/toxaphene/outfeeling/reforestize:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/uneducated/oxyosphresia/rosttra:output",
        "worthington/emmalynn/bouche/pearlings:output",
        "worthington/smoh/endospermous/multiplicate:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/cajole/lysolecithin/cvr:output",
        "worthington/smoh/endospermous/sharpens:output",
        "worthington/mithridatic/endospermous/parvoline:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_toxaphene_bedwarmer_yankeedom_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_toxaphene_bedwarmer_yankeedom_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_toxaphene_bedwarmer_yankeedom_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
