# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/prenominical/rsa/preinvolved:output",
        "bakongo/siccan/strikeboard/housebreaks:output",
        "bakongo/prenominical/generosities/inimicality:output",
        "bakongo/muscovade/generosities/salvationist:output",
        "bakongo/muscovade/strikeboard/mosslike:output",
        "bakongo/muscovade/rsa/jujubes:output",
        "bakongo/siccan/rsa/japanophobia:output",
        "bakongo/siccan/generosities/faddiest:output",
        "bakongo/muscovade/autoclaves/applicable:output",
        "bakongo/inchase/criminating/britte:output",
        "bakongo/prenominical/mechanism/dickie:output",
        "bakongo/prenominical/strikeboard/vitriolating:output",
        "bakongo/siccan/autoclaves/pulpaceous:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/muscovade/mechanism/juncoides:output",
        "bakongo/siccan/mechanism/foetalism:output",
        "bakongo/prenominical/autoclaves/deadeningly:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"emancipator_wisp_preinspector_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "emancipator_wisp_preinspector_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
