# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/hotbloods/criminating/nefreteted:output",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/compatibly/lysolecithin/compatibly:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/gnatcatcher/chimacum/steadite:output",
        "worthington/covering/endospermous/unpretending:output",
        "worthington/eclats/desaturation/patronizing:output",
        "worthington/eclats/chimacum/falconelle:output",
        "worthington/gnatcatcher/desaturation/uricemia:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_hotbloods_shinguard_senskell_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_hotbloods_shinguard_senskell_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_hotbloods_shinguard_senskell_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
