# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/moldableness/thrasher/endospermous/anilino:output",
        "worthington/moldableness/thrasher/endospermous/saprophytes:output",
        "worthington/moldableness/thrasher/endospermous/incase:output",
        "worthington/covering/endospermous/ganapati:output",
        "sizz/endospermous/farrington:output",
        "worthington/coverdale/endospermous/arbith:output",
        "worthington/kemppe/interlocked/delocalised:output",
        "worthington/smoh/endospermous/multiplicate:output",
        "sizz/endospermous/corsage:output",
        "sizz/hatchite/uncurd:output",
        "worthington/mithridatic/endospermous/filbert:output",
        "sizz/monogenies/scrawler:output",
        "worthington/moldableness/thrasher/endospermous/enormously:output",
        "sizz/endospermous/toxophilous:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/moldableness/thrasher/romipetal/ammonoidean:output",
        "worthington/moldableness/thrasher/endospermous/tutorials:output",
        "worthington/covering/endospermous/grimme:output",
        "worthington/covering/endospermous/slbm:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"sizz_tooter_abolished_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "sizz_tooter_abolished_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
