# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/stylosporous/solvents/tchervonetz/manikinism:output",
        "bakongo/diamantine/ofori/differen/sharia:output",
        "bakongo/stylosporous/solvents/backed/spaded:output",
        "emancipator/maier/lambdoid:output",
        "bakongo/diamantine/ofori/forsythe/genepi:output",
        "bakongo/stylosporous/solvents/geodesics/ellaville:output",
        "bakongo/upglide/endospermous/gulbenkian:output",
        "bakongo/kooks/cgx/raunchy:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/stylosporous/solvents/gwenda/colilysin:output",
        "emancipator/endospermous/tobaccoless:output",
        "emancipator/endospermous/signon:output",
        "bakongo/diamantine/ofori/endospermous/amah:output",
        "bakongo/upglide/endospermous/unflesh:output",
        "emancipator/endospermous/scyphiform:output",
        "bakongo/upglide/endospermous/ochreish:output",
        "bakongo/upglide/endospermous/kenoticism:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "bakongo/predisrupt/nubbiest/musicianly:output",
        "bakongo/diffluent/haircuts/leninabad:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"emancipator_aperients_tetryls_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["emancipator_aperients_tetryls_{chroot}/common_scripts/run_build.sh", "{chroot}", "emancipator_aperients_tetryls_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
