# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/mithridatic/endospermous/faizabad:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/alevins/criminating/bucconinae:output",
        "worthington/fulbright/reitman/ahem:output",
        "worthington/sweetiewife/emparadise/dimaggio:output",
        "worthington/backpacked/dustpans/minimized:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/mecodonta/recountless/mecodonta:output",
        "worthington/vocalistic/reitman/margarete:output",
        "worthington/cinenegative/vincas/adalbert:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/smoh/endospermous/multiplicate:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/cinenegative/lacertian/uninnately:output",
        "worthington/cinenegative/reitman/unalloyed:output",
        "worthington/mithridatic/endospermous/filbert:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_cinenegative_elastica_palsgraf_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_cinenegative_elastica_palsgraf_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_cinenegative_elastica_palsgraf_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
