# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "biomorphic/semitransept/endospermous/anomie:output",
        "biomorphic/keratosropy/unqueened/antennariid:output",
        "biomorphic/uncamp/bemire/tasimetric:output",
        "biomorphic/nimblewit/endospermous/hortorium:output",
        "biomorphic/spondylic/gnathostomi/snipish:output",
        "biomorphic/moochers/lysolecithin/moochers:output",
        "biomorphic/opportunism/lysolecithin/opportunism:output",
        "biomorphic/chromometer/lysolecithin/savelha:output",
        "biomorphic/fetwa/oxyosphresia/solanum:output",
        "biomorphic/semitransept/endospermous/nitriding:output",
        "biomorphic/lateraling/bemire/cotranspire:output",
        "biomorphic/galliano/criminating/telarly:output",
        "biomorphic/refiled/unqueened/nerves:output",
        "biomorphic/filaricidal/unqueened/lovel:output",
        "biomorphic/spondylic/lealness/inurements:output",
        "biomorphic/spondylic/kufiyeh/undergrowths:output",
        "biomorphic/semitransept/endospermous/demiseason:output",
        "biomorphic/chromometer/pirtleville/scufflers:output",
        "biomorphic/disequalize/titulation/disequalize:output",
        "biomorphic/spondylic/desaturation/centriscus:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"biomorphic_adventureful_triturature_unamiability_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["biomorphic_adventureful_triturature_unamiability_{chroot}/common_scripts/run_build.sh", "{chroot}", "biomorphic_adventureful_triturature_unamiability_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
