# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "biomorphic/outtrumped/stamina/nutricism/untotaled:output",
        "biomorphic/reinstitute/endospermous/lazzaroni:output",
        "biomorphic/cebian/qaid/prizefights:output",
        "biomorphic/reinstitute/endospermous/acacian:output",
        "biomorphic/semitransept/endospermous/biles:output",
        "biomorphic/reinstitute/endospermous/draftsman:output",
        "biomorphic/outtrumped/wrest/synanthetic/salicylous:output",
        "nonsovereign/endospermous/glimes:output",
        "biomorphic/reinstitute/endospermous/reemphasized:output",
        "biomorphic/untellable/surprise/pursuant:output",
        "biomorphic/reinstitute/endospermous/vitaminizing:output",
        "biomorphic/outtrumped/mennom/synanthetic/crossbarred:output",
        "biomorphic/outtrumped/stamina/vulcanising/parrotfish:output",
        "biomorphic/ananna/reitman/ananna:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"nonsovereign_idiolects_unrelatively_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["nonsovereign_idiolects_unrelatively_{chroot}/common_scripts/run_build.sh", "{chroot}", "nonsovereign_idiolects_unrelatively_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
