# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/covering/endospermous/brockages:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/moldableness/thrasher/endospermous/incase:output",
        "worthington/moldableness/thrasher/endospermous/saprophytes:output",
        "worthington/reteaching/bouche/strabismally:output",
        "worthington/illyes/kheths/milliers:output",
        "sizz/endospermous/farrington:output",
        "worthington/illyes/loathly/misadapts:output",
        "worthington/mithridatic/endospermous/filbert:output",
        "worthington/illyes/autoscopy/widowhood:output",
        "worthington/mithridatic/endospermous/parvoline:output",
        "worthington/moldableness/thrasher/endospermous/enormously:output",
        "worthington/seraphicness/slopstone/amboise:output",
        "worthington/seraphicness/vincas/overgladly:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/moldableness/thrasher/endospermous/tutorials:output",
        "worthington/covering/endospermous/grimme:output",
        "worthington/illyes/supernotably/cognised:output",
        "worthington/covering/endospermous/rabulistic:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"sizz_postparietal_fructiform_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["sizz_postparietal_fructiform_{chroot}/common_scripts/run_build.sh", "{chroot}", "sizz_postparietal_fructiform_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
