# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/stylosporous/solvents/lepsaria/eustache:output",
        "emancipator/endospermous/signon:output",
        "bakongo/stylosporous/solvents/boardroom/rockvale:output",
        "bakongo/diamantine/ofori/endospermous/amah:output",
        "bakongo/stylosporous/solvents/solvolyzed/trumperiness:output",
        "bakongo/upglide/endospermous/unflesh:output",
        "bakongo/diamantine/ofori/differen/sharia:output",
        "emancipator/endospermous/scyphiform:output",
        "emancipator/columbarium/geromorphism:output",
        "bakongo/upglide/endospermous/ochreish:output",
        "bakongo/diamantine/ofori/forsythe/genepi:output",
        "bakongo/stylosporous/solvents/owades/oxyopia:output",
        "bakongo/upglide/endospermous/gulbenkian:output",
        "bakongo/kooks/cgx/raunchy:output",
        "bakongo/upglide/endospermous/kenoticism:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/predisrupt/nubbiest/musicianly:output",
        "emancipator/endospermous/tobaccoless:output",
        "bakongo/diffluent/haircuts/leninabad:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"emancipator_jackdaws_marvel_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["emancipator_jackdaws_marvel_{chroot}/common_scripts/run_build.sh", "{chroot}", "emancipator_jackdaws_marvel_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
