# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/dividuity/criminating/resistingly:output",
        "bakongo/procaviidae/ferryville/buccula:output",
        "bakongo/dividuity/vincas/minisub:output",
        "bakongo/procaviidae/interhyal/nothous:output",
        "hypostasised/endospermous/bikinis:output",
        "bakongo/procaviidae/fetiales/thyrocricoid:output",
        "bakongo/did/whipmaking/colchicin:output",
        "bakongo/did/pneumas/southwood:output",
        "bakongo/did/santalum/billiton:output",
        "bakongo/did/syndeton/kittled:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "hypostasised/darkskin/tragopogon:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/procaviidae/gravitates/diaconicon:output",
        "hypostasised/motorbuses/heliosis:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"hypostasised_oldwives_lumme_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["hypostasised_oldwives_lumme_{chroot}/common_scripts/run_build.sh", "{chroot}", "hypostasised_oldwives_lumme_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
