# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/did/whipmaking/colchicin:output",
        "bakongo/upglide/endospermous/ultrafeudal:output",
        "bakongo/unequivalent/endospermous/unworthily:output",
        "bakongo/enophthalmos/criminating/slingers:output",
        "bakongo/panurgic/falltime/fighting:output",
        "bakongo/did/santalum/billiton:output",
        "bakongo/did/pneumas/southwood:output",
        "bakongo/did/syndeton/kittled:output",
        "bakongo/did/dustpans/unelegant:output",
        "bakongo/enophthalmos/shinguard/bocci:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/forcs/megalonyx/forcs:output",
        "bakongo/brunk/reitman/brunk:output",
        "bakongo/enophthalmos/vincas/outsnores:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"bakongo_stylosporous_antick_synanthetic_teleologies_antick_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["bakongo_stylosporous_antick_synanthetic_teleologies_{chroot}/common_scripts/run_build.sh", "{chroot}", "bakongo_stylosporous_antick_synanthetic_teleologies_antick_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
