# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/covering/endospermous/brockages:output",
        "worthington/unbraceleted/reitman/unbraceleted:output",
        "worthington/covering/endospermous/sparkingly:output",
        "worthington/beslaved/torbert/hadendowa:output",
        "worthington/viomycins/vincas/kuhnau:output",
        "worthington/alevins/criminating/bucconinae:output",
        "worthington/fulbright/reitman/ahem:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/vocalistic/reitman/margarete:output",
        "worthington/covering/endospermous/ganapati:output",
        "worthington/beslaved/epikia/plastochrone:output",
        "worthington/viomycins/reitman/stippled:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/beslaved/benedicta/neutralize:output",
        "worthington/covering/endospermous/goode:output",
        "worthington/cinenegative/reitman/unalloyed:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_viomycins_romipetal_semifixed_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_viomycins_romipetal_semifixed_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_viomycins_romipetal_semifixed_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
