# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
        ":output_sources",
        "bakongo/spiritlike/bemire/deceases:output",
        "bakongo/preconsuming/unqueened/mesogastral:output",
        "bakongo/waywode/unqueened/verbifies:output",
        "bakongo/upglide/endospermous/libau:output",
        "bakongo/aloxite/lysolecithin/hypural:output",
        "bakongo/ribaldly/unqueened/kerning:output",
        "bakongo/prolia/lysolecithin/reanalyzes:output",
        "bakongo/theanthropic/endospermous/bianka:output",
        "bakongo/upglide/endospermous/ultrafeudal:output",
        "bakongo/upglide/endospermous/netherstone:output",
        "bakongo/preconsuming/reliers/snecket:output",
        "bakongo/monofilm/oxyosphresia/ashpan:output",
        "bakongo/manipulating/lysolecithin/reimplanted:output",
        "bakongo/pobox/bemire/empiricism:output",
        "bakongo/stinkardly/unqueened/isopodous:output",
        "bakongo/snatchers/unqueened/redeemedness:output",
        "bakongo/prolia/pirtleville/ingmar:output",
        "bakongo/snatchers/reliers/antisexist:output",
        "bakongo/upglide/endospermous/physoclisti:output",
        "bakongo/upglide/endospermous/bounces:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
        "bakongo_upglide_endospermous_implemented_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["bakongo_upglide_endospermous_implemented_{chroot}/common_scripts/run_build.sh", "{chroot}", "bakongo_upglide_endospermous_implemented_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
