# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/diamantine/ofori/endospermous/chandi:output",
        "emancipator/dumbarton/teat:output",
        "bakongo/prolia/pirtleville/ingmar:output",
        "bakongo/diamantine/ofori/endospermous/amah:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/diamantine/ofori/romipetal/acidific:output",
        "emancipator/endospermous/scyphiform:output",
        "emancipator/dwain/bid:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"emancipator_insecuration_pointmaking_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "emancipator_insecuration_pointmaking_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
