# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "biomorphic/ninnyism/generosities/crasser:output",
        "biomorphic/afterwit/rsa/kirsches:output",
        "biomorphic/ninnyism/rsa/hematolytic:output",
        "biomorphic/tropophyte/criminating/bonorum:output",
        "biomorphic/gloveman/autoclaves/bergess:output",
        "biomorphic/ninnyism/autoclaves/allovers:output",
        "biomorphic/gloveman/generosities/thir:output",
        "biomorphic/ninnyism/strikeboard/spirography:output",
        "biomorphic/afterwit/generosities/epicalyx:output",
        "biomorphic/gloveman/mechanism/thilk:output",
        "biomorphic/afterwit/strikeboard/scientistic:output",
        "biomorphic/ninnyism/mechanism/coloquies:output",
        "biomorphic/gloveman/rsa/remiform:output",
        "biomorphic/untellable/surprise/pursuant:output",
        "biomorphic/afterwit/mechanism/diner:output",
        "biomorphic/gloveman/strikeboard/meacon:output",
        "biomorphic/afterwit/autoclaves/mesocarpic:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"nonsovereign_biocatalyst_chefornak_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "nonsovereign_biocatalyst_chefornak_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
