# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/sleided/urartaean/salomonic/pastorally:output",
        "worthington/rotherham/reitman/firmer:output",
        "worthington/rotherham/whalen/poulp:output",
        "worthington/rotherham/disenact/osteogenesis:output",
        "worthington/sleided/urartaean/spongioplasm/tantivy:output",
        "sizz/incipiency/klabund:output",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/sleided/urartaean/pygidia/scopeless:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/rotherham/undivested/televox:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/rotherham/redlining/junkdealer:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "sizz/niland/wantonlike:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/smoh/endospermous/multiplicate:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/rotherham/gowrie/rhatania:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"sizz_evander_chadars_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["sizz_evander_chadars_{chroot}/common_scripts/run_build.sh", "{chroot}", "sizz_evander_chadars_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
