# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/filiciform/synanthetic/unanalogous:output",
        "worthington/covering/endospermous/homilist:output",
        "sizz/plouky/scarlatina:output",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/barksome/unqueened/styloglossal:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/alevins/criminating/bucconinae:output",
        "worthington/cajole/pirtleville/unmaskers:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/knifing/synanthetic/cresive:output",
        "worthington/ihp/endospermous/elf:output",
        "worthington/viomycins/lysolecithin/windgalls:output",
        "sizz/solemnitude/titmarshian:output",
        "worthington/beslaved/benedicta/neutralize:output",
        "worthington/alevins/bemire/apoop:output",
        "worthington/pelomedusid/unqueened/pirrie:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"sizz_unlichened_tinsman_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "sizz_unlichened_tinsman_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
