# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/rotherham/outshooting/hookwise:output",
        "worthington/rotherham/reitman/firmer:output",
        "worthington/rotherham/whalen/poulp:output",
        "worthington/debtors/regioned/aips:output",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/rotherham/undivested/televox:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/coportion/algaesthesis/spongioplasm/hydrophidae:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/coportion/algaesthesis/pygidia/kauravas:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/coportion/algaesthesis/salomonic/hypocotyleal:output",
        "worthington/rotherham/gowrie/rhatania:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_coportion_algaesthesis_nongrieved_macrophagus_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_coportion_algaesthesis_nongrieved_macrophagus_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_coportion_algaesthesis_nongrieved_macrophagus_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
