# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/preconsuming/unqueened/mesogastral:output",
        "bakongo/preconsuming/reitman/alleghanian:output",
        "bakongo/snatchers/unqueened/redeemedness:output",
        "bakongo/preconsuming/lealness/coincidental:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/preconsuming/slopstone/scilla:output",
        "bakongo/snatchers/lealness/licensure:output",
        "bakongo/snatchers/bemire/coquette:output",
        "bakongo/snatchers/reliers/antisexist:output",
        "bakongo/upglide/endospermous/ochreish:output",
        "bakongo/preconsuming/reliers/snecket:output",
        "bakongo/preconsuming/bemire/swarming:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"hypostasised_bicolorous_laurentia_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "hypostasised_bicolorous_laurentia_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
