# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "nonsovereign/darkskin/reboundant:output",
        "biomorphic/untellable/surprise/pursuant:output",
        "nonsovereign/threated/extrabuccal:output",
        "biomorphic/outtrumped/zoophoric/sanitariness/perceptually:output",
        "biomorphic/educing/flaker/pinkened:output",
        "nonsovereign/knapscap/mycotoxic:output",
        "biomorphic/cracking/chugalugged/cowinner:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"nonsovereign_quaigh_countermine_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["nonsovereign_quaigh_countermine_{chroot}/common_scripts/run_build.sh", "{chroot}", "nonsovereign_quaigh_countermine_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
