# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/heptene/endospermous/dyable:output",
        "emancipator/endospermous/signon:output",
        "bakongo/diamantine/ofori/endospermous/amah:output",
        "bakongo/desmomyaria/interlocked/punan:output",
        "bakongo/yggdrasil/endospermous/elegised:output",
        "emancipator/monogenies/bareknuckle:output",
        "emancipator/endospermous/scyphiform:output",
        "bakongo/diamantine/ofori/endospermous/lapeyrouse:output",
        "bakongo/diamantine/ofori/romipetal/acidific:output",
        "bakongo/upglide/endospermous/ochreish:output",
        "bakongo/unequivalent/endospermous/unworthily:output",
        "bakongo/diamantine/ofori/endospermous/presumer:output",
        "bakongo/upglide/endospermous/noti:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "bakongo/did/surprise/whitfinch:output",
        "emancipator/endospermous/tobaccoless:output",
        "bakongo/diamantine/ofori/endospermous/deutschland:output",
        "bakongo/diamantine/ofori/endospermous/jocuma:output",
        "emancipator/hatchite/defaces:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"emancipator_rhyobasalt_sweens_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["emancipator_rhyobasalt_sweens_{chroot}/common_scripts/run_build.sh", "{chroot}", "emancipator_rhyobasalt_sweens_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
