# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/oxalacetate/glomerella/grynaeus:output",
        "bakongo/tlaco/preacquiring/faddisms:output",
        "bakongo/unsheathes/repossesses/gigs:output",
        "emancipator/routhercock/aristomachus:output",
        "bakongo/did/whipmaking/colchicin:output",
        "bakongo/listless/heuretic/outspit:output",
        "bakongo/stylosporous/areopagite/perchromate/umbrellaless:output",
        "bakongo/did/santalum/billiton:output",
        "bakongo/did/pneumas/southwood:output",
        "bakongo/did/syndeton/kittled:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/deadweight/studs/acatallactic:output",
        "emancipator/endospermous/tobaccoless:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"emancipator_copremias_niccolic_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["emancipator_copremias_niccolic_{chroot}/common_scripts/run_build.sh", "{chroot}", "emancipator_copremias_niccolic_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
