# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/spiritlike/bemire/deceases:output",
        "bakongo/acronyc/criminating/cothurns:output",
        "bakongo/waywode/unqueened/verbifies:output",
        "bakongo/upglide/endospermous/libau:output",
        "bakongo/aloxite/lysolecithin/hypural:output",
        "bakongo/prolia/lysolecithin/reanalyzes:output",
        "bakongo/reascension/lysolecithin/reascension:output",
        "bakongo/theanthropic/endospermous/bianka:output",
        "bakongo/monofilm/oxyosphresia/ashpan:output",
        "bakongo/pobox/bemire/empiricism:output",
        "bakongo/bastioned/unqueened/hormist:output",
        "bakongo/stinkardly/unqueened/isopodous:output",
        "bakongo/burfish/reitman/burfish:output",
        "bakongo/prolia/pirtleville/ingmar:output",
        "bakongo/upglide/endospermous/khoisan:output",
        "bakongo/upglide/endospermous/physoclisti:output",
        "bakongo/upglide/endospermous/bounces:output",
        "bakongo/upglide/endospermous/trustful:output",
        "bakongo/prolia/punak/uncork:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"bakongo_casabianca_lysolecithin_casabianca_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["bakongo_casabianca_lysolecithin_casabianca_{chroot}/common_scripts/run_build.sh", "{chroot}", "bakongo_casabianca_lysolecithin_casabianca_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
