# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "gpss/monogenies/antiegotism:output",
        "worthington/backpacked/surprise/torsibility:output",
        "gpss/endospermous/trinities:output",
        "worthington/moldableness/thrasher/endospermous/anilino:output",
        "worthington/moldableness/thrasher/endospermous/incase:output",
        "worthington/moldableness/thrasher/endospermous/saprophytes:output",
        "worthington/moldableness/thrasher/endospermous/enormously:output",
        "worthington/covering/endospermous/ganapati:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/coverdale/endospermous/arbith:output",
        "worthington/kemppe/interlocked/delocalised:output",
        "worthington/moldableness/thrasher/romipetal/ammonoidean:output",
        "gpss/hatchite/chanteuses:output",
        "worthington/smoh/endospermous/multiplicate:output",
        "gpss/endospermous/obtruder:output",
        "worthington/moldableness/thrasher/endospermous/tutorials:output",
        "worthington/covering/endospermous/slbm:output",
        "worthington/mithridatic/endospermous/filbert:output",
        "gpss/endospermous/chaves:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"gpss_dex_oversewn_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["gpss_dex_oversewn_{chroot}/common_scripts/run_build.sh", "{chroot}", "gpss_dex_oversewn_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
