# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/tensure/reitman/tensure:output",
        "worthington/covering/endospermous/sparkingly:output",
        "worthington/uncut/endospermous/naivenesses:output",
        "worthington/jujutsu/pseudoval/laupahoehoe:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/covering/endospermous/bemoisten:output",
        "worthington/jujutsu/reitman/dtg:output",
        "worthington/covering/endospermous/ganapati:output",
        "worthington/jujutsu/ermanno/blockages:output",
        "worthington/moldableness/thrasher/pratincola/blizzard:output",
        "worthington/uneducated/oxyosphresia/rosttra:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/uneducated/bouche/seanor:output",
        "worthington/covering/endospermous/pensileness:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_moldableness_thrasher_romipetal_metra_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_moldableness_thrasher_romipetal_metra_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_moldableness_thrasher_romipetal_metra_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
