# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/piazzi/burgers/idioretinal:output",
        "worthington/pathoses/workhorses/tunk:output",
        "worthington/coportion/mossful/ungrieved/abrahamidae:output",
        "worthington/pathoses/eot/kowalski:output",
        "worthington/backpacked/pneumas/pneumaticity:output",
        "worthington/backpacked/surprise/torsibility:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/backpacked/dustpans/minimized:output",
        "worthington/backpacked/syndeton/pensionary:output",
        "worthington/backpacked/whipmaking/uncoached:output",
        "worthington/pathoses/quaternionic/panside:output",
        "worthington/mayes/reitman/mayes:output",
        "worthington/backpacked/santalum/lespedeza:output",
        "worthington/pathoses/siamang/deracinating:output",
        "worthington/pathoses/phosphoreal/subform:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/mithridatic/endospermous/antiferment:output",
        "worthington/coportion/mossful/couthier/disserving:output",
        "worthington/hugeous/vincas/curkell:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_coportion_mossful_humour_contraries_mossful_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "worthington_coportion_mossful_humour_contraries_mossful_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
