# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "biomorphic/semitransept/endospermous/anomie:output",
        "biomorphic/semitransept/endospermous/thegn:output",
        "biomorphic/reinstitute/endospermous/nonbleach:output",
        "biomorphic/reinstitute/endospermous/lazzaroni:output",
        "nonsovereign/endospermous/squareman:output",
        "biomorphic/nucal/vincas/mordy:output",
        "biomorphic/reinstitute/endospermous/acacian:output",
        "biomorphic/outtrumped/postsign/synanthetic/unutilized:output",
        "biomorphic/semitransept/endospermous/biles:output",
        "biomorphic/semitransept/endospermous/algonkins:output",
        "biomorphic/eruditions/chugalugged/cyclorrhapha:output",
        "biomorphic/cracking/routhercock/kitabi:output",
        "nonsovereign/endospermous/glimes:output",
        "biomorphic/reinstitute/endospermous/reemphasized:output",
        "biomorphic/untellable/surprise/pursuant:output",
        "biomorphic/marshland/singlestep/trichoptera:output",
        "biomorphic/chromometer/pirtleville/scufflers:output",
        "biomorphic/eruditions/routhercock/zolaesque:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"nonsovereign_odontoplast_screigh_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["nonsovereign_odontoplast_screigh_{chroot}/common_scripts/run_build.sh", "{chroot}", "nonsovereign_odontoplast_screigh_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
