# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/subhymenium/substantize/firearmed:output",
        "worthington/subhymenium/posted/tima:output",
        "worthington/subhymenium/criminating/odorless:output",
        "worthington/subhymenium/wots/bottier:output",
        "worthington/subhymenium/spruiker/gorakhpur:output",
        "worthington/subhymenium/subcuneus/impetrating:output",
        "worthington/subhymenium/flub/bateful:output",
        "worthington/subhymenium/fumulus/nirles:output",
        "worthington/unfishable/reitman/unfishable:output",
        "worthington/subhymenium/hereditably/interruptive:output",
        "worthington/subhymenium/desaturation/deludingly:output",
        "worthington/moldableness/thrasher/endospermous/cnossus:output",
        "worthington/subhymenium/redondilla/doodlers:output",
        "worthington/subhymenium/trypa/preterhuman:output",
        "worthington/subhymenium/strychnos/claretta:output",
        "worthington/subhymenium/flavian/imnaha:output",
        "worthington/subhymenium/chimacum/estamin:output",
        "worthington/subhymenium/decemvii/clankless:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_subhymenium_brainteaser_crenature_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_subhymenium_brainteaser_crenature_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_subhymenium_brainteaser_crenature_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
