# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
        ":output_sources",
        "worthington/covering/endospermous/sparkingly:output",
        "worthington/covering/endospermous/spr:output",
        "worthington/uncut/endospermous/naivenesses:output",
        "worthington/uneducated/reitman/ruing:output",
        "worthington/covering/endospermous/adamical:output",
        "worthington/covering/endospermous/twaddy:output",
        "worthington/covering/endospermous/ganapati:output",
        "worthington/slaveless/reitman/slaveless:output",
        "worthington/desiring/reitman/desiring:output",
        "worthington/monoid/reitman/monoid:output",
        "worthington/covering/endospermous/uteropexia:output",
        "worthington/covering/endospermous/sublimers:output",
        "worthington/kenai/reitman/kenai:output",
        "worthington/covering/endospermous/pensileness:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
        "worthington_moldableness_transverter_endospermous_snooziness_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "worthington_moldableness_transverter_endospermous_snooziness_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
