# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/puparia/hereditably/pupilability:output",
        "bakongo/tagboard/reitman/tagboard:output",
        "bakongo/diamantine/ofori/endospermous/amah:output",
        "bakongo/upglide/endospermous/jnanayoga:output",
        "hypostasised/endospermous/tulipomania:output",
        "bakongo/upglide/endospermous/tarred:output",
        "bakongo/puparia/springvale/byssine:output",
        "hypostasised/endospermous/onlaying:output",
        "bakongo/upglide/endospermous/kenoticism:output",
        "bakongo/did/surprise/whitfinch:output",
        "bakongo/heptene/endospermous/disjasket:output",
        "hypostasised/routhercock/alloted:output",
        "bakongo/upglide/endospermous/trustful:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"hypostasised_synergidal_studium_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["hypostasised_synergidal_studium_{chroot}/common_scripts/run_build.sh", "{chroot}", "hypostasised_synergidal_studium_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
