# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

shell_sources(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "bakongo/theanthropic/endospermous/bianka:output",
        "bakongo/upglide/endospermous/unflesh:output",
        "bakongo/manipulating/lysolecithin/reimplanted:output",
        "bakongo/upglide/endospermous/heathberry:output",
        "bakongo/upglide/endospermous/ultrafeudal:output",
        "bakongo/manipulating/bouche/monoazo:output",
        "bakongo/manipulating/bouche/monoazo:output",
        "bakongo/manipulating/lysolecithin/reimplanted:output",
        "bakongo/upglide/endospermous/vividnesses:output",
        "bakongo/diamantine/ofori/quarrelproof/antilacrosse:output",
        "bakongo/gastrelcosis/berseems/subclerk:output",
        "bakongo/upglide/endospermous/relaxers:output",
        "bakongo/upglide/endospermous/khoisan:output",
        "bakongo/upglide/endospermous/phantomship:output",
        "bakongo/diamantine/ofori/endospermous/deutschland:output",
        "bakongo/diamantine/ofori/endospermous/jocuma:output",
        "bakongo/upglide/endospermous/bounces:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"bakongo_diamantine_ofori_featheredges_rant_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["bakongo_diamantine_ofori_featheredges_rant_{chroot}/common_scripts/run_build.sh", "{chroot}", "bakongo_diamantine_ofori_featheredges_rant_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
