# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "biomorphic/reinstitute/endospermous/acacian:output",
        "biomorphic/outtrumped/hauula/chickories/blubberingly:output",
        "biomorphic/puerpery/endospermous/zoning:output",
        "biomorphic/untellable/whipmaking/prig:output",
        "biomorphic/outtrumped/hauula/audrey/tribometer:output",
        "biomorphic/reinstitute/endospermous/reemphasized:output",
        "nonsovereign/endospermous/glimes:output",
        "biomorphic/untellable/surprise/pursuant:output",
        "biomorphic/refiled/unqueened/nerves:output",
        "biomorphic/rewey/vincas/bodiless:output",
        "biomorphic/reinstitute/endospermous/vitaminizing:output",
        "nonsovereign/bicolorous/acquisitor:output",
        "biomorphic/untellable/pneumas/inimaginable:output",
        "biomorphic/untellable/syndeton/alfur:output",
        "biomorphic/untellable/santalum/rejuvenator:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"nonsovereign_seels_apotheosize_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["{chroot}/geomorphy/run_build.sh", "{chroot}", "nonsovereign_seels_apotheosize_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
