# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

files(
    name="output_sources",
    sources=[
        "test.txt",
        "random_seed_01.txt",
        "random_seed_02.txt",
        "random_seed_03.txt",
        "random_seed_04.txt",
        "random_seed_05.txt",
        "random_seed_06.txt",
        "random_seed_07.txt",
        "random_seed_08.txt",
        "random_seed_09.txt",
        "random_seed_10.txt",
        "random_seed_11.txt",
    ],
)

adhoc_tool(
    name="output",
    execution_dependencies=[
":output_sources",
        "worthington/lituoline/gnathostomi/gournay:output",
        "worthington/catalogers/lealness/unswanlike:output",
        "worthington/catalogers/chimacum/waldglas:output",
        "worthington/catalogers/haircuts/bhadon:output",
        "worthington/catalogers/gnathostomi/hamathite:output",
        "worthington/lituoline/kufiyeh/secularism:output",
        "worthington/unfishable/reitman/unfishable:output",
        "worthington/lituoline/haircuts/outhunts:output",
        "worthington/catalogers/kufiyeh/sayce:output",
        "worthington/lituoline/chimacum/kaczer:output",
        "worthington/lituoline/lealness/fervor:output",
        "worthington/catalogers/speciosity/upbrast:output",
        "worthington/fango/ermanno/pillorize:output",
        "worthington/fango/criminating/coeff:output",
        "worthington/catalogers/desaturation/pectinatella:output",
        "worthington/lituoline/speciosity/thonotosassa:output",
        "worthington/lituoline/desaturation/mythopoetry:output",
        "geomorphy:run_build_script",
    ],
    output_files=[
"worthington_moldableness_thrasher_iotization_mephitism_output.txt",
    ],
    runnable="geomorphy:bash",
    args=["worthington_moldableness_thrasher_iotization_mephitism_{chroot}/common_scripts/run_build.sh", "{chroot}", "worthington_moldableness_thrasher_iotization_mephitism_output.txt",],
    runnable_dependencies=[
        "geomorphy:cat",
        "geomorphy:md5sum",
        "geomorphy:cut",
    ],
)
